---

services:
  database:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: avmb123
    volumes:
    - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    ports:
    - "3306:3306"
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
    - "5000:5000"