-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 15:50:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poc` DEFAULT CHARACTER SET utf8 ;
USE `poc` ;

-- -----------------------------------------------------
-- Table `poc`.`comunidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poc`.`comunidades` (
  `idcomunidades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomunidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poc`.`colecoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poc`.`colecoes` (
  `idcolecoes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `comunidades_idcomunidades` INT NOT NULL,
  PRIMARY KEY (`idcolecoes`),
  INDEX `fk_colecoes_comunidades_idx` (`comunidades_idcomunidades` ASC) VISIBLE,
  CONSTRAINT `fk_colecoes_comunidades`
    FOREIGN KEY (`comunidades_idcomunidades`)
    REFERENCES `poc`.`comunidades` (`idcomunidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poc`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poc`.`itens` (
  `iditens` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `colecoes_idcolecoes` INT NOT NULL,
  PRIMARY KEY (`iditens`),
  INDEX `fk_itens_colecoes1_idx` (`colecoes_idcolecoes` ASC) VISIBLE,
  CONSTRAINT `fk_itens_colecoes1`
    FOREIGN KEY (`colecoes_idcolecoes`)
    REFERENCES `poc`.`colecoes` (`idcolecoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poc`.`bitstreams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poc`.`bitstreams` (
  `idbitstreams` INT NOT NULL AUTO_INCREMENT,
  `nomeArquivo` VARCHAR(45) NULL,
  `pacote` VARCHAR(45) NULL,
  `itens_iditens` INT NOT NULL,
  PRIMARY KEY (`idbitstreams`),
  INDEX `fk_bitstreams_itens1_idx` (`itens_iditens` ASC) VISIBLE,
  CONSTRAINT `fk_bitstreams_itens1`
    FOREIGN KEY (`itens_iditens`)
    REFERENCES `poc`.`itens` (`iditens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
